/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as HomeRouteImport } from './routes/_home'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as HomeIndexRouteImport } from './routes/_home/index'
import { Route as HomePetsRouteImport } from './routes/_home/pets'
import { Route as HomeAboutRouteImport } from './routes/_home/about'
import { Route as AuthSignupRouteImport } from './routes/_auth/signup'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as HomePetIdRouteImport } from './routes/_home/pet/$id'

const HomeRoute = HomeRouteImport.update({
  id: '/_home',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeIndexRoute = HomeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HomeRoute,
} as any)
const HomePetsRoute = HomePetsRouteImport.update({
  id: '/pets',
  path: '/pets',
  getParentRoute: () => HomeRoute,
} as any)
const HomeAboutRoute = HomeAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => HomeRoute,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const HomePetIdRoute = HomePetIdRouteImport.update({
  id: '/pet/$id',
  path: '/pet/$id',
  getParentRoute: () => HomeRoute,
} as any)

export interface FileRoutesByFullPath {
  '/login': typeof AuthLoginRoute
  '/signup': typeof AuthSignupRoute
  '/about': typeof HomeAboutRoute
  '/pets': typeof HomePetsRoute
  '/': typeof HomeIndexRoute
  '/pet/$id': typeof HomePetIdRoute
}
export interface FileRoutesByTo {
  '/login': typeof AuthLoginRoute
  '/signup': typeof AuthSignupRoute
  '/about': typeof HomeAboutRoute
  '/pets': typeof HomePetsRoute
  '/': typeof HomeIndexRoute
  '/pet/$id': typeof HomePetIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/_home': typeof HomeRouteWithChildren
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/signup': typeof AuthSignupRoute
  '/_home/about': typeof HomeAboutRoute
  '/_home/pets': typeof HomePetsRoute
  '/_home/': typeof HomeIndexRoute
  '/_home/pet/$id': typeof HomePetIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/login' | '/signup' | '/about' | '/pets' | '/' | '/pet/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/login' | '/signup' | '/about' | '/pets' | '/' | '/pet/$id'
  id:
    | '__root__'
    | '/_auth'
    | '/_home'
    | '/_auth/login'
    | '/_auth/signup'
    | '/_home/about'
    | '/_home/pets'
    | '/_home/'
    | '/_home/pet/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  HomeRoute: typeof HomeRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_home': {
      id: '/_home'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_home/': {
      id: '/_home/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof HomeIndexRouteImport
      parentRoute: typeof HomeRoute
    }
    '/_home/pets': {
      id: '/_home/pets'
      path: '/pets'
      fullPath: '/pets'
      preLoaderRoute: typeof HomePetsRouteImport
      parentRoute: typeof HomeRoute
    }
    '/_home/about': {
      id: '/_home/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof HomeAboutRouteImport
      parentRoute: typeof HomeRoute
    }
    '/_auth/signup': {
      id: '/_auth/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_home/pet/$id': {
      id: '/_home/pet/$id'
      path: '/pet/$id'
      fullPath: '/pet/$id'
      preLoaderRoute: typeof HomePetIdRouteImport
      parentRoute: typeof HomeRoute
    }
  }
}

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignupRoute: typeof AuthSignupRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthSignupRoute: AuthSignupRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface HomeRouteChildren {
  HomeAboutRoute: typeof HomeAboutRoute
  HomePetsRoute: typeof HomePetsRoute
  HomeIndexRoute: typeof HomeIndexRoute
  HomePetIdRoute: typeof HomePetIdRoute
}

const HomeRouteChildren: HomeRouteChildren = {
  HomeAboutRoute: HomeAboutRoute,
  HomePetsRoute: HomePetsRoute,
  HomeIndexRoute: HomeIndexRoute,
  HomePetIdRoute: HomePetIdRoute,
}

const HomeRouteWithChildren = HomeRoute._addFileChildren(HomeRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  HomeRoute: HomeRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
